variable "prefix" {}
variable "location" {}
variable "resourcegroup_name" {}
variable "subnet_id" {}
variable "subnet_prefix" {}
variable "site1_hostname" {}
variable "site1_cert" {}
variable "site1_cert_password" {}
variable "public_ip_prefix_id" {}
